/**
 * Created by aleksei on 5/10/17.
 */
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const errors = {
  WRONG_CREDENTIALS: 'WRONG_CREDENTIALS',
  CONNECTION_ERROR: 'CONNECTION_ERROR',
  ACCOUNT_EXPIRED: 'ACCOUNT_EXPIRED',
};
export const SET_FILTER = 'SET_FILTER';
export const SET_DATE = 'SET_DATE';
export const SET_KEYWORD = 'SET_KEYWORD';
export const SET_DATE_PICKER_VISIBILITY = 'SET_DATE_PICKER_VISIBILITY';
export const SET_OPTION_NAME = 'SET_OPTION_NAME';
export const SET_VARIANTS = 'SET_VARIANTS';
export const SET_SORT_BY = 'SET_SORT_BY';
